{% set name = "xmle" %}
{% set version = "0.1.19" %}
{% set checksum = "509ef2381c37a0a52aad529778c43884e48a00eeca65f7d87461751dd402be99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jpn--/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas

test:
  imports:
    - xmle

about:
  home: https://github.com/jpn--/xmle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'xml extension for generating neatly formatted HTML output from a variety of object types'
  dev_url: https://github.com/jpn--/xmle

extra:
  recipe-maintainers:
    - jpn--
